//////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                          //
//      MST Utility Library                                                                 //
//      Copyright (c)2026 Martinus Terpstra                                                 //
//                                                                                          //
//      Permission is hereby granted, free of charge, to any person obtaining a copy        //
//      of this software and associated documentation files (the "Software"), to deal       //
//      in the Software without restriction, including without limitation the rights        //
//      to use, copy, modify, merge, publish, distribute, sublicense, and/or sell           //
//      copies of the Software, and to permit persons to whom the Software is               //
//      furnished to do so, subject to the following conditions:                            //
//                                                                                          //
//      The above copyright notice and this permission notice shall be included in          //
//      all copies or substantial portions of the Software.                                 //
//                                                                                          //
//      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR          //
//      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,            //
//      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE         //
//      AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER              //
//      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,       //
//      OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN           //
//      THE SOFTWARE.                                                                       //
//                                                                                          //
//////////////////////////////////////////////////////////////////////////////////////////////

#include <catch2/catch_test_macros.hpp>

#include <set_assertions.h>

#include "helpers.h"

#include <mmath2.h>
#include <mcommon.h>

using mst::math::vector;
namespace swizzle = mst::math::swizzle;

/* every swizzle::<components>(vec) free function is generated by the _mst_declare_swizzle*
	macros in mx_math_vector.h -- one function per accessible component-letter combination for
	each vector<V,1..4>. These test cases enumerate all of them (472 in total) rather than a
	sample, since the value of each is entirely in getting the component order right and a
	hand-picked sample would leave the rest unchecked. */

TEST_CASE("vector<V,1>: swizzle:: free functions (exhaustive)", "[vector][swizzle]")
{
	vector<float, 1> v1(1);

	/* 2-component results */
	REQUIRE(swizzle::xx(v1) == vector<float, 2>(v1.x, v1.x));
	/* 3-component results */
	REQUIRE(swizzle::xxx(v1) == vector<float, 3>(v1.x, v1.x, v1.x));
	/* 4-component results */
	REQUIRE(swizzle::xxxx(v1) == vector<float, 4>(v1.x, v1.x, v1.x, v1.x));
}

TEST_CASE("vector<V,2>: swizzle:: free functions (exhaustive)", "[vector][swizzle]")
{
	vector<float, 2> v2(1, 2);

	/* 2-component results */
	REQUIRE(swizzle::xx(v2) == vector<float, 2>(v2.x, v2.x));
	REQUIRE(swizzle::xy(v2) == vector<float, 2>(v2.x, v2.y));
	REQUIRE(swizzle::yx(v2) == vector<float, 2>(v2.y, v2.x));
	REQUIRE(swizzle::yy(v2) == vector<float, 2>(v2.y, v2.y));
	/* 3-component results */
	REQUIRE(swizzle::xxx(v2) == vector<float, 3>(v2.x, v2.x, v2.x));
	REQUIRE(swizzle::xxy(v2) == vector<float, 3>(v2.x, v2.x, v2.y));
	REQUIRE(swizzle::xyx(v2) == vector<float, 3>(v2.x, v2.y, v2.x));
	REQUIRE(swizzle::xyy(v2) == vector<float, 3>(v2.x, v2.y, v2.y));
	REQUIRE(swizzle::yxx(v2) == vector<float, 3>(v2.y, v2.x, v2.x));
	REQUIRE(swizzle::yxy(v2) == vector<float, 3>(v2.y, v2.x, v2.y));
	REQUIRE(swizzle::yyx(v2) == vector<float, 3>(v2.y, v2.y, v2.x));
	REQUIRE(swizzle::yyy(v2) == vector<float, 3>(v2.y, v2.y, v2.y));
	/* 4-component results */
	REQUIRE(swizzle::xxxx(v2) == vector<float, 4>(v2.x, v2.x, v2.x, v2.x));
	REQUIRE(swizzle::xxxy(v2) == vector<float, 4>(v2.x, v2.x, v2.x, v2.y));
	REQUIRE(swizzle::xxyx(v2) == vector<float, 4>(v2.x, v2.x, v2.y, v2.x));
	REQUIRE(swizzle::xxyy(v2) == vector<float, 4>(v2.x, v2.x, v2.y, v2.y));
	REQUIRE(swizzle::xyxx(v2) == vector<float, 4>(v2.x, v2.y, v2.x, v2.x));
	REQUIRE(swizzle::xyxy(v2) == vector<float, 4>(v2.x, v2.y, v2.x, v2.y));
	REQUIRE(swizzle::xyyx(v2) == vector<float, 4>(v2.x, v2.y, v2.y, v2.x));
	REQUIRE(swizzle::xyyy(v2) == vector<float, 4>(v2.x, v2.y, v2.y, v2.y));
	REQUIRE(swizzle::yxxx(v2) == vector<float, 4>(v2.y, v2.x, v2.x, v2.x));
	REQUIRE(swizzle::yxxy(v2) == vector<float, 4>(v2.y, v2.x, v2.x, v2.y));
	REQUIRE(swizzle::yxyx(v2) == vector<float, 4>(v2.y, v2.x, v2.y, v2.x));
	REQUIRE(swizzle::yxyy(v2) == vector<float, 4>(v2.y, v2.x, v2.y, v2.y));
	REQUIRE(swizzle::yyxx(v2) == vector<float, 4>(v2.y, v2.y, v2.x, v2.x));
	REQUIRE(swizzle::yyxy(v2) == vector<float, 4>(v2.y, v2.y, v2.x, v2.y));
	REQUIRE(swizzle::yyyx(v2) == vector<float, 4>(v2.y, v2.y, v2.y, v2.x));
	REQUIRE(swizzle::yyyy(v2) == vector<float, 4>(v2.y, v2.y, v2.y, v2.y));
}

TEST_CASE("vector<V,3>: swizzle:: free functions (exhaustive)", "[vector][swizzle]")
{
	vector<float, 3> v3(1, 2, 3);

	/* 2-component results */
	REQUIRE(swizzle::xx(v3) == vector<float, 2>(v3.x, v3.x));
	REQUIRE(swizzle::xy(v3) == vector<float, 2>(v3.x, v3.y));
	REQUIRE(swizzle::xz(v3) == vector<float, 2>(v3.x, v3.z));
	REQUIRE(swizzle::yx(v3) == vector<float, 2>(v3.y, v3.x));
	REQUIRE(swizzle::yy(v3) == vector<float, 2>(v3.y, v3.y));
	REQUIRE(swizzle::yz(v3) == vector<float, 2>(v3.y, v3.z));
	REQUIRE(swizzle::zx(v3) == vector<float, 2>(v3.z, v3.x));
	REQUIRE(swizzle::zy(v3) == vector<float, 2>(v3.z, v3.y));
	REQUIRE(swizzle::zz(v3) == vector<float, 2>(v3.z, v3.z));
	/* 3-component results */
	REQUIRE(swizzle::xxx(v3) == vector<float, 3>(v3.x, v3.x, v3.x));
	REQUIRE(swizzle::xxy(v3) == vector<float, 3>(v3.x, v3.x, v3.y));
	REQUIRE(swizzle::xxz(v3) == vector<float, 3>(v3.x, v3.x, v3.z));
	REQUIRE(swizzle::xyx(v3) == vector<float, 3>(v3.x, v3.y, v3.x));
	REQUIRE(swizzle::xyy(v3) == vector<float, 3>(v3.x, v3.y, v3.y));
	REQUIRE(swizzle::xyz(v3) == vector<float, 3>(v3.x, v3.y, v3.z));
	REQUIRE(swizzle::xzx(v3) == vector<float, 3>(v3.x, v3.z, v3.x));
	REQUIRE(swizzle::xzy(v3) == vector<float, 3>(v3.x, v3.z, v3.y));
	REQUIRE(swizzle::xzz(v3) == vector<float, 3>(v3.x, v3.z, v3.z));
	REQUIRE(swizzle::yxx(v3) == vector<float, 3>(v3.y, v3.x, v3.x));
	REQUIRE(swizzle::yxy(v3) == vector<float, 3>(v3.y, v3.x, v3.y));
	REQUIRE(swizzle::yxz(v3) == vector<float, 3>(v3.y, v3.x, v3.z));
	REQUIRE(swizzle::yyx(v3) == vector<float, 3>(v3.y, v3.y, v3.x));
	REQUIRE(swizzle::yyy(v3) == vector<float, 3>(v3.y, v3.y, v3.y));
	REQUIRE(swizzle::yyz(v3) == vector<float, 3>(v3.y, v3.y, v3.z));
	REQUIRE(swizzle::yzx(v3) == vector<float, 3>(v3.y, v3.z, v3.x));
	REQUIRE(swizzle::yzy(v3) == vector<float, 3>(v3.y, v3.z, v3.y));
	REQUIRE(swizzle::yzz(v3) == vector<float, 3>(v3.y, v3.z, v3.z));
	REQUIRE(swizzle::zxx(v3) == vector<float, 3>(v3.z, v3.x, v3.x));
	REQUIRE(swizzle::zxy(v3) == vector<float, 3>(v3.z, v3.x, v3.y));
	REQUIRE(swizzle::zxz(v3) == vector<float, 3>(v3.z, v3.x, v3.z));
	REQUIRE(swizzle::zyx(v3) == vector<float, 3>(v3.z, v3.y, v3.x));
	REQUIRE(swizzle::zyy(v3) == vector<float, 3>(v3.z, v3.y, v3.y));
	REQUIRE(swizzle::zyz(v3) == vector<float, 3>(v3.z, v3.y, v3.z));
	REQUIRE(swizzle::zzx(v3) == vector<float, 3>(v3.z, v3.z, v3.x));
	REQUIRE(swizzle::zzy(v3) == vector<float, 3>(v3.z, v3.z, v3.y));
	REQUIRE(swizzle::zzz(v3) == vector<float, 3>(v3.z, v3.z, v3.z));
	/* 4-component results */
	REQUIRE(swizzle::xxxy(v3) == vector<float, 4>(v3.x, v3.x, v3.x, v3.y));
	REQUIRE(swizzle::xxxz(v3) == vector<float, 4>(v3.x, v3.x, v3.x, v3.z));
	REQUIRE(swizzle::xxyx(v3) == vector<float, 4>(v3.x, v3.x, v3.y, v3.x));
	REQUIRE(swizzle::xxyy(v3) == vector<float, 4>(v3.x, v3.x, v3.y, v3.y));
	REQUIRE(swizzle::xxyz(v3) == vector<float, 4>(v3.x, v3.x, v3.y, v3.z));
	REQUIRE(swizzle::xxzx(v3) == vector<float, 4>(v3.x, v3.x, v3.z, v3.x));
	REQUIRE(swizzle::xxzy(v3) == vector<float, 4>(v3.x, v3.x, v3.z, v3.y));
	REQUIRE(swizzle::xxzz(v3) == vector<float, 4>(v3.x, v3.x, v3.z, v3.z));
	REQUIRE(swizzle::xyxx(v3) == vector<float, 4>(v3.x, v3.y, v3.x, v3.x));
	REQUIRE(swizzle::xyxy(v3) == vector<float, 4>(v3.x, v3.y, v3.x, v3.y));
	REQUIRE(swizzle::xyxz(v3) == vector<float, 4>(v3.x, v3.y, v3.x, v3.z));
	REQUIRE(swizzle::xyyx(v3) == vector<float, 4>(v3.x, v3.y, v3.y, v3.x));
	REQUIRE(swizzle::xyyy(v3) == vector<float, 4>(v3.x, v3.y, v3.y, v3.y));
	REQUIRE(swizzle::xyyz(v3) == vector<float, 4>(v3.x, v3.y, v3.y, v3.z));
	REQUIRE(swizzle::xyzx(v3) == vector<float, 4>(v3.x, v3.y, v3.z, v3.x));
	REQUIRE(swizzle::xyzy(v3) == vector<float, 4>(v3.x, v3.y, v3.z, v3.y));
	REQUIRE(swizzle::xyzz(v3) == vector<float, 4>(v3.x, v3.y, v3.z, v3.z));
	REQUIRE(swizzle::xzxx(v3) == vector<float, 4>(v3.x, v3.z, v3.x, v3.x));
	REQUIRE(swizzle::xzxy(v3) == vector<float, 4>(v3.x, v3.z, v3.x, v3.y));
	REQUIRE(swizzle::xzxz(v3) == vector<float, 4>(v3.x, v3.z, v3.x, v3.z));
	REQUIRE(swizzle::xzyx(v3) == vector<float, 4>(v3.x, v3.z, v3.y, v3.x));
	REQUIRE(swizzle::xzyy(v3) == vector<float, 4>(v3.x, v3.z, v3.y, v3.y));
	REQUIRE(swizzle::xzyz(v3) == vector<float, 4>(v3.x, v3.z, v3.y, v3.z));
	REQUIRE(swizzle::xzzx(v3) == vector<float, 4>(v3.x, v3.z, v3.z, v3.x));
	REQUIRE(swizzle::xzzy(v3) == vector<float, 4>(v3.x, v3.z, v3.z, v3.y));
	REQUIRE(swizzle::xzzz(v3) == vector<float, 4>(v3.x, v3.z, v3.z, v3.z));
	REQUIRE(swizzle::yxxx(v3) == vector<float, 4>(v3.y, v3.x, v3.x, v3.x));
	REQUIRE(swizzle::yxxy(v3) == vector<float, 4>(v3.y, v3.x, v3.x, v3.y));
	REQUIRE(swizzle::yxxz(v3) == vector<float, 4>(v3.y, v3.x, v3.x, v3.z));
	REQUIRE(swizzle::yxyx(v3) == vector<float, 4>(v3.y, v3.x, v3.y, v3.x));
	REQUIRE(swizzle::yxyy(v3) == vector<float, 4>(v3.y, v3.x, v3.y, v3.y));
	REQUIRE(swizzle::yxyz(v3) == vector<float, 4>(v3.y, v3.x, v3.y, v3.z));
	REQUIRE(swizzle::yxzx(v3) == vector<float, 4>(v3.y, v3.x, v3.z, v3.x));
	REQUIRE(swizzle::yxzy(v3) == vector<float, 4>(v3.y, v3.x, v3.z, v3.y));
	REQUIRE(swizzle::yxzz(v3) == vector<float, 4>(v3.y, v3.x, v3.z, v3.z));
	REQUIRE(swizzle::yyxx(v3) == vector<float, 4>(v3.y, v3.y, v3.x, v3.x));
	REQUIRE(swizzle::yyxy(v3) == vector<float, 4>(v3.y, v3.y, v3.x, v3.y));
	REQUIRE(swizzle::yyxz(v3) == vector<float, 4>(v3.y, v3.y, v3.x, v3.z));
	REQUIRE(swizzle::yyyx(v3) == vector<float, 4>(v3.y, v3.y, v3.y, v3.x));
	REQUIRE(swizzle::yyyz(v3) == vector<float, 4>(v3.y, v3.y, v3.y, v3.z));
	REQUIRE(swizzle::yyzx(v3) == vector<float, 4>(v3.y, v3.y, v3.z, v3.x));
	REQUIRE(swizzle::yyzy(v3) == vector<float, 4>(v3.y, v3.y, v3.z, v3.y));
	REQUIRE(swizzle::yyzz(v3) == vector<float, 4>(v3.y, v3.y, v3.z, v3.z));
	REQUIRE(swizzle::yzxx(v3) == vector<float, 4>(v3.y, v3.z, v3.x, v3.x));
	REQUIRE(swizzle::yzxy(v3) == vector<float, 4>(v3.y, v3.z, v3.x, v3.y));
	REQUIRE(swizzle::yzxz(v3) == vector<float, 4>(v3.y, v3.z, v3.x, v3.z));
	REQUIRE(swizzle::yzyx(v3) == vector<float, 4>(v3.y, v3.z, v3.y, v3.x));
	REQUIRE(swizzle::yzyy(v3) == vector<float, 4>(v3.y, v3.z, v3.y, v3.y));
	REQUIRE(swizzle::yzyz(v3) == vector<float, 4>(v3.y, v3.z, v3.y, v3.z));
	REQUIRE(swizzle::yzzx(v3) == vector<float, 4>(v3.y, v3.z, v3.z, v3.x));
	REQUIRE(swizzle::yzzy(v3) == vector<float, 4>(v3.y, v3.z, v3.z, v3.y));
	REQUIRE(swizzle::yzzz(v3) == vector<float, 4>(v3.y, v3.z, v3.z, v3.z));
	REQUIRE(swizzle::zxxx(v3) == vector<float, 4>(v3.z, v3.x, v3.x, v3.x));
	REQUIRE(swizzle::zxxy(v3) == vector<float, 4>(v3.z, v3.x, v3.x, v3.y));
	REQUIRE(swizzle::zxxz(v3) == vector<float, 4>(v3.z, v3.x, v3.x, v3.z));
	REQUIRE(swizzle::zxyx(v3) == vector<float, 4>(v3.z, v3.x, v3.y, v3.x));
	REQUIRE(swizzle::zxyy(v3) == vector<float, 4>(v3.z, v3.x, v3.y, v3.y));
	REQUIRE(swizzle::zxyz(v3) == vector<float, 4>(v3.z, v3.x, v3.y, v3.z));
	REQUIRE(swizzle::zxzx(v3) == vector<float, 4>(v3.z, v3.x, v3.z, v3.x));
	REQUIRE(swizzle::zxzy(v3) == vector<float, 4>(v3.z, v3.x, v3.z, v3.y));
	REQUIRE(swizzle::zxzz(v3) == vector<float, 4>(v3.z, v3.x, v3.z, v3.z));
	REQUIRE(swizzle::zyxx(v3) == vector<float, 4>(v3.z, v3.y, v3.x, v3.x));
	REQUIRE(swizzle::zyxy(v3) == vector<float, 4>(v3.z, v3.y, v3.x, v3.y));
	REQUIRE(swizzle::zyxz(v3) == vector<float, 4>(v3.z, v3.y, v3.x, v3.z));
	REQUIRE(swizzle::zyyx(v3) == vector<float, 4>(v3.z, v3.y, v3.y, v3.x));
	REQUIRE(swizzle::zyyy(v3) == vector<float, 4>(v3.z, v3.y, v3.y, v3.y));
	REQUIRE(swizzle::zyyz(v3) == vector<float, 4>(v3.z, v3.y, v3.y, v3.z));
	REQUIRE(swizzle::zyzx(v3) == vector<float, 4>(v3.z, v3.y, v3.z, v3.x));
	REQUIRE(swizzle::zyzy(v3) == vector<float, 4>(v3.z, v3.y, v3.z, v3.y));
	REQUIRE(swizzle::zyzz(v3) == vector<float, 4>(v3.z, v3.y, v3.z, v3.z));
	REQUIRE(swizzle::zzxx(v3) == vector<float, 4>(v3.z, v3.z, v3.x, v3.x));
	REQUIRE(swizzle::zzxy(v3) == vector<float, 4>(v3.z, v3.z, v3.x, v3.y));
	REQUIRE(swizzle::zzxz(v3) == vector<float, 4>(v3.z, v3.z, v3.x, v3.z));
	REQUIRE(swizzle::zzyx(v3) == vector<float, 4>(v3.z, v3.z, v3.y, v3.x));
	REQUIRE(swizzle::zzyy(v3) == vector<float, 4>(v3.z, v3.z, v3.y, v3.y));
	REQUIRE(swizzle::zzyz(v3) == vector<float, 4>(v3.z, v3.z, v3.y, v3.z));
	REQUIRE(swizzle::zzzx(v3) == vector<float, 4>(v3.z, v3.z, v3.z, v3.x));
	REQUIRE(swizzle::zzzy(v3) == vector<float, 4>(v3.z, v3.z, v3.z, v3.y));
}

TEST_CASE("vector<V,4>: swizzle:: free functions (exhaustive)", "[vector][swizzle]")
{
	vector<float, 4> v4(1, 2, 3, 4);

	/* 2-component results */
	REQUIRE(swizzle::ww(v4) == vector<float, 2>(v4.w, v4.w));
	REQUIRE(swizzle::wx(v4) == vector<float, 2>(v4.w, v4.x));
	REQUIRE(swizzle::wy(v4) == vector<float, 2>(v4.w, v4.y));
	REQUIRE(swizzle::wz(v4) == vector<float, 2>(v4.w, v4.z));
	REQUIRE(swizzle::xw(v4) == vector<float, 2>(v4.x, v4.w));
	REQUIRE(swizzle::xx(v4) == vector<float, 2>(v4.x, v4.x));
	REQUIRE(swizzle::xy(v4) == vector<float, 2>(v4.x, v4.y));
	REQUIRE(swizzle::xz(v4) == vector<float, 2>(v4.x, v4.z));
	REQUIRE(swizzle::yw(v4) == vector<float, 2>(v4.y, v4.w));
	REQUIRE(swizzle::yx(v4) == vector<float, 2>(v4.y, v4.x));
	REQUIRE(swizzle::yy(v4) == vector<float, 2>(v4.y, v4.y));
	REQUIRE(swizzle::yz(v4) == vector<float, 2>(v4.y, v4.z));
	REQUIRE(swizzle::zw(v4) == vector<float, 2>(v4.z, v4.w));
	REQUIRE(swizzle::zx(v4) == vector<float, 2>(v4.z, v4.x));
	REQUIRE(swizzle::zy(v4) == vector<float, 2>(v4.z, v4.y));
	REQUIRE(swizzle::zz(v4) == vector<float, 2>(v4.z, v4.z));
	/* 3-component results */
	REQUIRE(swizzle::www(v4) == vector<float, 3>(v4.w, v4.w, v4.w));
	REQUIRE(swizzle::wwx(v4) == vector<float, 3>(v4.w, v4.w, v4.x));
	REQUIRE(swizzle::wwy(v4) == vector<float, 3>(v4.w, v4.w, v4.y));
	REQUIRE(swizzle::wwz(v4) == vector<float, 3>(v4.w, v4.w, v4.z));
	REQUIRE(swizzle::wxw(v4) == vector<float, 3>(v4.w, v4.x, v4.w));
	REQUIRE(swizzle::wxx(v4) == vector<float, 3>(v4.w, v4.x, v4.x));
	REQUIRE(swizzle::wxy(v4) == vector<float, 3>(v4.w, v4.x, v4.y));
	REQUIRE(swizzle::wxz(v4) == vector<float, 3>(v4.w, v4.x, v4.z));
	REQUIRE(swizzle::wyw(v4) == vector<float, 3>(v4.w, v4.y, v4.w));
	REQUIRE(swizzle::wyx(v4) == vector<float, 3>(v4.w, v4.y, v4.x));
	REQUIRE(swizzle::wyy(v4) == vector<float, 3>(v4.w, v4.y, v4.y));
	REQUIRE(swizzle::wyz(v4) == vector<float, 3>(v4.w, v4.y, v4.z));
	REQUIRE(swizzle::wzw(v4) == vector<float, 3>(v4.w, v4.z, v4.w));
	REQUIRE(swizzle::wzx(v4) == vector<float, 3>(v4.w, v4.z, v4.x));
	REQUIRE(swizzle::wzy(v4) == vector<float, 3>(v4.w, v4.z, v4.y));
	REQUIRE(swizzle::wzz(v4) == vector<float, 3>(v4.w, v4.z, v4.z));
	REQUIRE(swizzle::xww(v4) == vector<float, 3>(v4.x, v4.w, v4.w));
	REQUIRE(swizzle::xwx(v4) == vector<float, 3>(v4.x, v4.w, v4.x));
	REQUIRE(swizzle::xwy(v4) == vector<float, 3>(v4.x, v4.w, v4.y));
	REQUIRE(swizzle::xwz(v4) == vector<float, 3>(v4.x, v4.w, v4.z));
	REQUIRE(swizzle::xxw(v4) == vector<float, 3>(v4.x, v4.x, v4.w));
	REQUIRE(swizzle::xxx(v4) == vector<float, 3>(v4.x, v4.x, v4.x));
	REQUIRE(swizzle::xxy(v4) == vector<float, 3>(v4.x, v4.x, v4.y));
	REQUIRE(swizzle::xxz(v4) == vector<float, 3>(v4.x, v4.x, v4.z));
	REQUIRE(swizzle::xyw(v4) == vector<float, 3>(v4.x, v4.y, v4.w));
	REQUIRE(swizzle::xyx(v4) == vector<float, 3>(v4.x, v4.y, v4.x));
	REQUIRE(swizzle::xyy(v4) == vector<float, 3>(v4.x, v4.y, v4.y));
	REQUIRE(swizzle::xyz(v4) == vector<float, 3>(v4.x, v4.y, v4.z));
	REQUIRE(swizzle::xzw(v4) == vector<float, 3>(v4.x, v4.z, v4.w));
	REQUIRE(swizzle::xzx(v4) == vector<float, 3>(v4.x, v4.z, v4.x));
	REQUIRE(swizzle::xzy(v4) == vector<float, 3>(v4.x, v4.z, v4.y));
	REQUIRE(swizzle::xzz(v4) == vector<float, 3>(v4.x, v4.z, v4.z));
	REQUIRE(swizzle::yww(v4) == vector<float, 3>(v4.y, v4.w, v4.w));
	REQUIRE(swizzle::ywx(v4) == vector<float, 3>(v4.y, v4.w, v4.x));
	REQUIRE(swizzle::ywy(v4) == vector<float, 3>(v4.y, v4.w, v4.y));
	REQUIRE(swizzle::ywz(v4) == vector<float, 3>(v4.y, v4.w, v4.z));
	REQUIRE(swizzle::yxw(v4) == vector<float, 3>(v4.y, v4.x, v4.w));
	REQUIRE(swizzle::yxx(v4) == vector<float, 3>(v4.y, v4.x, v4.x));
	REQUIRE(swizzle::yxy(v4) == vector<float, 3>(v4.y, v4.x, v4.y));
	REQUIRE(swizzle::yxz(v4) == vector<float, 3>(v4.y, v4.x, v4.z));
	REQUIRE(swizzle::yyw(v4) == vector<float, 3>(v4.y, v4.y, v4.w));
	REQUIRE(swizzle::yyx(v4) == vector<float, 3>(v4.y, v4.y, v4.x));
	REQUIRE(swizzle::yyy(v4) == vector<float, 3>(v4.y, v4.y, v4.y));
	REQUIRE(swizzle::yyz(v4) == vector<float, 3>(v4.y, v4.y, v4.z));
	REQUIRE(swizzle::yzw(v4) == vector<float, 3>(v4.y, v4.z, v4.w));
	REQUIRE(swizzle::yzx(v4) == vector<float, 3>(v4.y, v4.z, v4.x));
	REQUIRE(swizzle::yzy(v4) == vector<float, 3>(v4.y, v4.z, v4.y));
	REQUIRE(swizzle::yzz(v4) == vector<float, 3>(v4.y, v4.z, v4.z));
	REQUIRE(swizzle::zww(v4) == vector<float, 3>(v4.z, v4.w, v4.w));
	REQUIRE(swizzle::zwx(v4) == vector<float, 3>(v4.z, v4.w, v4.x));
	REQUIRE(swizzle::zwy(v4) == vector<float, 3>(v4.z, v4.w, v4.y));
	REQUIRE(swizzle::zwz(v4) == vector<float, 3>(v4.z, v4.w, v4.z));
	REQUIRE(swizzle::zxw(v4) == vector<float, 3>(v4.z, v4.x, v4.w));
	REQUIRE(swizzle::zxx(v4) == vector<float, 3>(v4.z, v4.x, v4.x));
	REQUIRE(swizzle::zxy(v4) == vector<float, 3>(v4.z, v4.x, v4.y));
	REQUIRE(swizzle::zxz(v4) == vector<float, 3>(v4.z, v4.x, v4.z));
	REQUIRE(swizzle::zyw(v4) == vector<float, 3>(v4.z, v4.y, v4.w));
	REQUIRE(swizzle::zyx(v4) == vector<float, 3>(v4.z, v4.y, v4.x));
	REQUIRE(swizzle::zyy(v4) == vector<float, 3>(v4.z, v4.y, v4.y));
	REQUIRE(swizzle::zyz(v4) == vector<float, 3>(v4.z, v4.y, v4.z));
	REQUIRE(swizzle::zzw(v4) == vector<float, 3>(v4.z, v4.z, v4.w));
	REQUIRE(swizzle::zzx(v4) == vector<float, 3>(v4.z, v4.z, v4.x));
	REQUIRE(swizzle::zzy(v4) == vector<float, 3>(v4.z, v4.z, v4.y));
	REQUIRE(swizzle::zzz(v4) == vector<float, 3>(v4.z, v4.z, v4.z));
	/* 4-component results */
	REQUIRE(swizzle::wwww(v4) == vector<float, 4>(v4.w, v4.w, v4.w, v4.w));
	REQUIRE(swizzle::wwwx(v4) == vector<float, 4>(v4.w, v4.w, v4.w, v4.x));
	REQUIRE(swizzle::wwwy(v4) == vector<float, 4>(v4.w, v4.w, v4.w, v4.y));
	REQUIRE(swizzle::wwwz(v4) == vector<float, 4>(v4.w, v4.w, v4.w, v4.z));
	REQUIRE(swizzle::wwxw(v4) == vector<float, 4>(v4.w, v4.w, v4.x, v4.w));
	REQUIRE(swizzle::wwxx(v4) == vector<float, 4>(v4.w, v4.w, v4.x, v4.x));
	REQUIRE(swizzle::wwxy(v4) == vector<float, 4>(v4.w, v4.w, v4.x, v4.y));
	REQUIRE(swizzle::wwxz(v4) == vector<float, 4>(v4.w, v4.w, v4.x, v4.z));
	REQUIRE(swizzle::wwyw(v4) == vector<float, 4>(v4.w, v4.w, v4.y, v4.w));
	REQUIRE(swizzle::wwyx(v4) == vector<float, 4>(v4.w, v4.w, v4.y, v4.x));
	REQUIRE(swizzle::wwyy(v4) == vector<float, 4>(v4.w, v4.w, v4.y, v4.y));
	REQUIRE(swizzle::wwyz(v4) == vector<float, 4>(v4.w, v4.w, v4.y, v4.z));
	REQUIRE(swizzle::wwzw(v4) == vector<float, 4>(v4.w, v4.w, v4.z, v4.w));
	REQUIRE(swizzle::wwzx(v4) == vector<float, 4>(v4.w, v4.w, v4.z, v4.x));
	REQUIRE(swizzle::wwzy(v4) == vector<float, 4>(v4.w, v4.w, v4.z, v4.y));
	REQUIRE(swizzle::wwzz(v4) == vector<float, 4>(v4.w, v4.w, v4.z, v4.z));
	REQUIRE(swizzle::wxww(v4) == vector<float, 4>(v4.w, v4.x, v4.w, v4.w));
	REQUIRE(swizzle::wxwx(v4) == vector<float, 4>(v4.w, v4.x, v4.w, v4.x));
	REQUIRE(swizzle::wxwy(v4) == vector<float, 4>(v4.w, v4.x, v4.w, v4.y));
	REQUIRE(swizzle::wxwz(v4) == vector<float, 4>(v4.w, v4.x, v4.w, v4.z));
	REQUIRE(swizzle::wxxw(v4) == vector<float, 4>(v4.w, v4.x, v4.x, v4.w));
	REQUIRE(swizzle::wxxx(v4) == vector<float, 4>(v4.w, v4.x, v4.x, v4.x));
	REQUIRE(swizzle::wxxy(v4) == vector<float, 4>(v4.w, v4.x, v4.x, v4.y));
	REQUIRE(swizzle::wxxz(v4) == vector<float, 4>(v4.w, v4.x, v4.x, v4.z));
	REQUIRE(swizzle::wxyw(v4) == vector<float, 4>(v4.w, v4.x, v4.y, v4.w));
	REQUIRE(swizzle::wxyx(v4) == vector<float, 4>(v4.w, v4.x, v4.y, v4.x));
	REQUIRE(swizzle::wxyy(v4) == vector<float, 4>(v4.w, v4.x, v4.y, v4.y));
	REQUIRE(swizzle::wxzw(v4) == vector<float, 4>(v4.w, v4.x, v4.z, v4.w));
	REQUIRE(swizzle::wxzx(v4) == vector<float, 4>(v4.w, v4.x, v4.z, v4.x));
	REQUIRE(swizzle::wxzz(v4) == vector<float, 4>(v4.w, v4.x, v4.z, v4.z));
	REQUIRE(swizzle::wyww(v4) == vector<float, 4>(v4.w, v4.y, v4.w, v4.w));
	REQUIRE(swizzle::wywx(v4) == vector<float, 4>(v4.w, v4.y, v4.w, v4.x));
	REQUIRE(swizzle::wywy(v4) == vector<float, 4>(v4.w, v4.y, v4.w, v4.y));
	REQUIRE(swizzle::wywz(v4) == vector<float, 4>(v4.w, v4.y, v4.w, v4.z));
	REQUIRE(swizzle::wyxw(v4) == vector<float, 4>(v4.w, v4.y, v4.x, v4.w));
	REQUIRE(swizzle::wyxx(v4) == vector<float, 4>(v4.w, v4.y, v4.x, v4.x));
	REQUIRE(swizzle::wyxy(v4) == vector<float, 4>(v4.w, v4.y, v4.x, v4.y));
	REQUIRE(swizzle::wyyw(v4) == vector<float, 4>(v4.w, v4.y, v4.y, v4.w));
	REQUIRE(swizzle::wyyx(v4) == vector<float, 4>(v4.w, v4.y, v4.y, v4.x));
	REQUIRE(swizzle::wyyy(v4) == vector<float, 4>(v4.w, v4.y, v4.y, v4.y));
	REQUIRE(swizzle::wyyz(v4) == vector<float, 4>(v4.w, v4.y, v4.y, v4.z));
	REQUIRE(swizzle::wyzw(v4) == vector<float, 4>(v4.w, v4.y, v4.z, v4.w));
	REQUIRE(swizzle::wyzy(v4) == vector<float, 4>(v4.w, v4.y, v4.z, v4.y));
	REQUIRE(swizzle::wyzz(v4) == vector<float, 4>(v4.w, v4.y, v4.z, v4.z));
	REQUIRE(swizzle::wzww(v4) == vector<float, 4>(v4.w, v4.z, v4.w, v4.w));
	REQUIRE(swizzle::wzwx(v4) == vector<float, 4>(v4.w, v4.z, v4.w, v4.x));
	REQUIRE(swizzle::wzwy(v4) == vector<float, 4>(v4.w, v4.z, v4.w, v4.y));
	REQUIRE(swizzle::wzwz(v4) == vector<float, 4>(v4.w, v4.z, v4.w, v4.z));
	REQUIRE(swizzle::wzxw(v4) == vector<float, 4>(v4.w, v4.z, v4.x, v4.w));
	REQUIRE(swizzle::wzxx(v4) == vector<float, 4>(v4.w, v4.z, v4.x, v4.x));
	REQUIRE(swizzle::wzxz(v4) == vector<float, 4>(v4.w, v4.z, v4.x, v4.z));
	REQUIRE(swizzle::wzyw(v4) == vector<float, 4>(v4.w, v4.z, v4.y, v4.w));
	REQUIRE(swizzle::wzyy(v4) == vector<float, 4>(v4.w, v4.z, v4.y, v4.y));
	REQUIRE(swizzle::wzyz(v4) == vector<float, 4>(v4.w, v4.z, v4.y, v4.z));
	REQUIRE(swizzle::wzzw(v4) == vector<float, 4>(v4.w, v4.z, v4.z, v4.w));
	REQUIRE(swizzle::wzzx(v4) == vector<float, 4>(v4.w, v4.z, v4.z, v4.x));
	REQUIRE(swizzle::wzzy(v4) == vector<float, 4>(v4.w, v4.z, v4.z, v4.y));
	REQUIRE(swizzle::wzzz(v4) == vector<float, 4>(v4.w, v4.z, v4.z, v4.z));
	REQUIRE(swizzle::xwww(v4) == vector<float, 4>(v4.x, v4.w, v4.w, v4.w));
	REQUIRE(swizzle::xwwx(v4) == vector<float, 4>(v4.x, v4.w, v4.w, v4.x));
	REQUIRE(swizzle::xwwy(v4) == vector<float, 4>(v4.x, v4.w, v4.w, v4.y));
	REQUIRE(swizzle::xwwz(v4) == vector<float, 4>(v4.x, v4.w, v4.w, v4.z));
	REQUIRE(swizzle::xwxw(v4) == vector<float, 4>(v4.x, v4.w, v4.x, v4.w));
	REQUIRE(swizzle::xwxx(v4) == vector<float, 4>(v4.x, v4.w, v4.x, v4.x));
	REQUIRE(swizzle::xwxy(v4) == vector<float, 4>(v4.x, v4.w, v4.x, v4.y));
	REQUIRE(swizzle::xwxz(v4) == vector<float, 4>(v4.x, v4.w, v4.x, v4.z));
	REQUIRE(swizzle::xwyw(v4) == vector<float, 4>(v4.x, v4.w, v4.y, v4.w));
	REQUIRE(swizzle::xwyx(v4) == vector<float, 4>(v4.x, v4.w, v4.y, v4.x));
	REQUIRE(swizzle::xwyy(v4) == vector<float, 4>(v4.x, v4.w, v4.y, v4.y));
	REQUIRE(swizzle::xwzw(v4) == vector<float, 4>(v4.x, v4.w, v4.z, v4.w));
	REQUIRE(swizzle::xwzx(v4) == vector<float, 4>(v4.x, v4.w, v4.z, v4.x));
	REQUIRE(swizzle::xwzz(v4) == vector<float, 4>(v4.x, v4.w, v4.z, v4.z));
	REQUIRE(swizzle::xxww(v4) == vector<float, 4>(v4.x, v4.x, v4.w, v4.w));
	REQUIRE(swizzle::xxwx(v4) == vector<float, 4>(v4.x, v4.x, v4.w, v4.x));
	REQUIRE(swizzle::xxwy(v4) == vector<float, 4>(v4.x, v4.x, v4.w, v4.y));
	REQUIRE(swizzle::xxwz(v4) == vector<float, 4>(v4.x, v4.x, v4.w, v4.z));
	REQUIRE(swizzle::xxxw(v4) == vector<float, 4>(v4.x, v4.x, v4.x, v4.w));
	REQUIRE(swizzle::xxxx(v4) == vector<float, 4>(v4.x, v4.x, v4.x, v4.x));
	REQUIRE(swizzle::xxxy(v4) == vector<float, 4>(v4.x, v4.x, v4.x, v4.y));
	REQUIRE(swizzle::xxxz(v4) == vector<float, 4>(v4.x, v4.x, v4.x, v4.z));
	REQUIRE(swizzle::xxyw(v4) == vector<float, 4>(v4.x, v4.x, v4.y, v4.w));
	REQUIRE(swizzle::xxyx(v4) == vector<float, 4>(v4.x, v4.x, v4.y, v4.x));
	REQUIRE(swizzle::xxyy(v4) == vector<float, 4>(v4.x, v4.x, v4.y, v4.y));
	REQUIRE(swizzle::xxyz(v4) == vector<float, 4>(v4.x, v4.x, v4.y, v4.z));
	REQUIRE(swizzle::xxzw(v4) == vector<float, 4>(v4.x, v4.x, v4.z, v4.w));
	REQUIRE(swizzle::xxzx(v4) == vector<float, 4>(v4.x, v4.x, v4.z, v4.x));
	REQUIRE(swizzle::xxzy(v4) == vector<float, 4>(v4.x, v4.x, v4.z, v4.y));
	REQUIRE(swizzle::xxzz(v4) == vector<float, 4>(v4.x, v4.x, v4.z, v4.z));
	REQUIRE(swizzle::xyww(v4) == vector<float, 4>(v4.x, v4.y, v4.w, v4.w));
	REQUIRE(swizzle::xywx(v4) == vector<float, 4>(v4.x, v4.y, v4.w, v4.x));
	REQUIRE(swizzle::xywy(v4) == vector<float, 4>(v4.x, v4.y, v4.w, v4.y));
	REQUIRE(swizzle::xyxw(v4) == vector<float, 4>(v4.x, v4.y, v4.x, v4.w));
	REQUIRE(swizzle::xyxx(v4) == vector<float, 4>(v4.x, v4.y, v4.x, v4.x));
	REQUIRE(swizzle::xyxy(v4) == vector<float, 4>(v4.x, v4.y, v4.x, v4.y));
	REQUIRE(swizzle::xyxz(v4) == vector<float, 4>(v4.x, v4.y, v4.x, v4.z));
	REQUIRE(swizzle::xyyw(v4) == vector<float, 4>(v4.x, v4.y, v4.y, v4.w));
	REQUIRE(swizzle::xyyx(v4) == vector<float, 4>(v4.x, v4.y, v4.y, v4.x));
	REQUIRE(swizzle::xyyy(v4) == vector<float, 4>(v4.x, v4.y, v4.y, v4.y));
	REQUIRE(swizzle::xyyz(v4) == vector<float, 4>(v4.x, v4.y, v4.y, v4.z));
	REQUIRE(swizzle::xyzw(v4) == vector<float, 4>(v4.x, v4.y, v4.z, v4.w));
	REQUIRE(swizzle::xyzx(v4) == vector<float, 4>(v4.x, v4.y, v4.z, v4.x));
	REQUIRE(swizzle::xyzy(v4) == vector<float, 4>(v4.x, v4.y, v4.z, v4.y));
	REQUIRE(swizzle::xyzz(v4) == vector<float, 4>(v4.x, v4.y, v4.z, v4.z));
	REQUIRE(swizzle::xzww(v4) == vector<float, 4>(v4.x, v4.z, v4.w, v4.w));
	REQUIRE(swizzle::xzwx(v4) == vector<float, 4>(v4.x, v4.z, v4.w, v4.x));
	REQUIRE(swizzle::xzwy(v4) == vector<float, 4>(v4.x, v4.z, v4.w, v4.y));
	REQUIRE(swizzle::xzwz(v4) == vector<float, 4>(v4.x, v4.z, v4.w, v4.z));
	REQUIRE(swizzle::xzxw(v4) == vector<float, 4>(v4.x, v4.z, v4.x, v4.w));
	REQUIRE(swizzle::xzxx(v4) == vector<float, 4>(v4.x, v4.z, v4.x, v4.x));
	REQUIRE(swizzle::xzxy(v4) == vector<float, 4>(v4.x, v4.z, v4.x, v4.y));
	REQUIRE(swizzle::xzxz(v4) == vector<float, 4>(v4.x, v4.z, v4.x, v4.z));
	REQUIRE(swizzle::xzyw(v4) == vector<float, 4>(v4.x, v4.z, v4.y, v4.w));
	REQUIRE(swizzle::xzyx(v4) == vector<float, 4>(v4.x, v4.z, v4.y, v4.x));
	REQUIRE(swizzle::xzyy(v4) == vector<float, 4>(v4.x, v4.z, v4.y, v4.y));
	REQUIRE(swizzle::xzyz(v4) == vector<float, 4>(v4.x, v4.z, v4.y, v4.z));
	REQUIRE(swizzle::xzzw(v4) == vector<float, 4>(v4.x, v4.z, v4.z, v4.w));
	REQUIRE(swizzle::xzzx(v4) == vector<float, 4>(v4.x, v4.z, v4.z, v4.x));
	REQUIRE(swizzle::xzzy(v4) == vector<float, 4>(v4.x, v4.z, v4.z, v4.y));
	REQUIRE(swizzle::xzzz(v4) == vector<float, 4>(v4.x, v4.z, v4.z, v4.z));
	REQUIRE(swizzle::ywww(v4) == vector<float, 4>(v4.y, v4.w, v4.w, v4.w));
	REQUIRE(swizzle::ywwx(v4) == vector<float, 4>(v4.y, v4.w, v4.w, v4.x));
	REQUIRE(swizzle::ywwy(v4) == vector<float, 4>(v4.y, v4.w, v4.w, v4.y));
	REQUIRE(swizzle::ywwz(v4) == vector<float, 4>(v4.y, v4.w, v4.w, v4.z));
	REQUIRE(swizzle::ywxw(v4) == vector<float, 4>(v4.y, v4.w, v4.x, v4.w));
	REQUIRE(swizzle::ywxx(v4) == vector<float, 4>(v4.y, v4.w, v4.x, v4.x));
	REQUIRE(swizzle::ywxy(v4) == vector<float, 4>(v4.y, v4.w, v4.x, v4.y));
	REQUIRE(swizzle::ywxz(v4) == vector<float, 4>(v4.y, v4.w, v4.x, v4.z));
	REQUIRE(swizzle::ywyw(v4) == vector<float, 4>(v4.y, v4.w, v4.y, v4.w));
	REQUIRE(swizzle::ywyx(v4) == vector<float, 4>(v4.y, v4.w, v4.y, v4.x));
	REQUIRE(swizzle::ywyy(v4) == vector<float, 4>(v4.y, v4.w, v4.y, v4.y));
	REQUIRE(swizzle::ywyz(v4) == vector<float, 4>(v4.y, v4.w, v4.y, v4.z));
	REQUIRE(swizzle::ywzw(v4) == vector<float, 4>(v4.y, v4.w, v4.z, v4.w));
	REQUIRE(swizzle::ywzx(v4) == vector<float, 4>(v4.y, v4.w, v4.z, v4.x));
	REQUIRE(swizzle::ywzy(v4) == vector<float, 4>(v4.y, v4.w, v4.z, v4.y));
	REQUIRE(swizzle::ywzz(v4) == vector<float, 4>(v4.y, v4.w, v4.z, v4.z));
	REQUIRE(swizzle::yxww(v4) == vector<float, 4>(v4.y, v4.x, v4.w, v4.w));
	REQUIRE(swizzle::yxwx(v4) == vector<float, 4>(v4.y, v4.x, v4.w, v4.x));
	REQUIRE(swizzle::yxwy(v4) == vector<float, 4>(v4.y, v4.x, v4.w, v4.y));
	REQUIRE(swizzle::yxwz(v4) == vector<float, 4>(v4.y, v4.x, v4.w, v4.z));
	REQUIRE(swizzle::yxxw(v4) == vector<float, 4>(v4.y, v4.x, v4.x, v4.w));
	REQUIRE(swizzle::yxxx(v4) == vector<float, 4>(v4.y, v4.x, v4.x, v4.x));
	REQUIRE(swizzle::yxxy(v4) == vector<float, 4>(v4.y, v4.x, v4.x, v4.y));
	REQUIRE(swizzle::yxxz(v4) == vector<float, 4>(v4.y, v4.x, v4.x, v4.z));
	REQUIRE(swizzle::yxyw(v4) == vector<float, 4>(v4.y, v4.x, v4.y, v4.w));
	REQUIRE(swizzle::yxyx(v4) == vector<float, 4>(v4.y, v4.x, v4.y, v4.x));
	REQUIRE(swizzle::yxyy(v4) == vector<float, 4>(v4.y, v4.x, v4.y, v4.y));
	REQUIRE(swizzle::yxyz(v4) == vector<float, 4>(v4.y, v4.x, v4.y, v4.z));
	REQUIRE(swizzle::yxzw(v4) == vector<float, 4>(v4.y, v4.x, v4.z, v4.w));
	REQUIRE(swizzle::yxzx(v4) == vector<float, 4>(v4.y, v4.x, v4.z, v4.x));
	REQUIRE(swizzle::yxzy(v4) == vector<float, 4>(v4.y, v4.x, v4.z, v4.y));
	REQUIRE(swizzle::yxzz(v4) == vector<float, 4>(v4.y, v4.x, v4.z, v4.z));
	REQUIRE(swizzle::yyww(v4) == vector<float, 4>(v4.y, v4.y, v4.w, v4.w));
	REQUIRE(swizzle::yywx(v4) == vector<float, 4>(v4.y, v4.y, v4.w, v4.x));
	REQUIRE(swizzle::yywy(v4) == vector<float, 4>(v4.y, v4.y, v4.w, v4.y));
	REQUIRE(swizzle::yywz(v4) == vector<float, 4>(v4.y, v4.y, v4.w, v4.z));
	REQUIRE(swizzle::yyxw(v4) == vector<float, 4>(v4.y, v4.y, v4.x, v4.w));
	REQUIRE(swizzle::yyxx(v4) == vector<float, 4>(v4.y, v4.y, v4.x, v4.x));
	REQUIRE(swizzle::yyxy(v4) == vector<float, 4>(v4.y, v4.y, v4.x, v4.y));
	REQUIRE(swizzle::yyxz(v4) == vector<float, 4>(v4.y, v4.y, v4.x, v4.z));
	REQUIRE(swizzle::yyyw(v4) == vector<float, 4>(v4.y, v4.y, v4.y, v4.w));
	REQUIRE(swizzle::yyyx(v4) == vector<float, 4>(v4.y, v4.y, v4.y, v4.x));
	REQUIRE(swizzle::yyyy(v4) == vector<float, 4>(v4.y, v4.y, v4.y, v4.y));
	REQUIRE(swizzle::yyyz(v4) == vector<float, 4>(v4.y, v4.y, v4.y, v4.z));
	REQUIRE(swizzle::yyzw(v4) == vector<float, 4>(v4.y, v4.y, v4.z, v4.w));
	REQUIRE(swizzle::yyzx(v4) == vector<float, 4>(v4.y, v4.y, v4.z, v4.x));
	REQUIRE(swizzle::yyzy(v4) == vector<float, 4>(v4.y, v4.y, v4.z, v4.y));
	REQUIRE(swizzle::yyzz(v4) == vector<float, 4>(v4.y, v4.y, v4.z, v4.z));
	REQUIRE(swizzle::yzww(v4) == vector<float, 4>(v4.y, v4.z, v4.w, v4.w));
	REQUIRE(swizzle::yzwx(v4) == vector<float, 4>(v4.y, v4.z, v4.w, v4.x));
	REQUIRE(swizzle::yzwy(v4) == vector<float, 4>(v4.y, v4.z, v4.w, v4.y));
	REQUIRE(swizzle::yzwz(v4) == vector<float, 4>(v4.y, v4.z, v4.w, v4.z));
	REQUIRE(swizzle::yzxw(v4) == vector<float, 4>(v4.y, v4.z, v4.x, v4.w));
	REQUIRE(swizzle::yzxx(v4) == vector<float, 4>(v4.y, v4.z, v4.x, v4.x));
	REQUIRE(swizzle::yzxy(v4) == vector<float, 4>(v4.y, v4.z, v4.x, v4.y));
	REQUIRE(swizzle::yzxz(v4) == vector<float, 4>(v4.y, v4.z, v4.x, v4.z));
	REQUIRE(swizzle::yzyw(v4) == vector<float, 4>(v4.y, v4.z, v4.y, v4.w));
	REQUIRE(swizzle::yzyx(v4) == vector<float, 4>(v4.y, v4.z, v4.y, v4.x));
	REQUIRE(swizzle::yzyy(v4) == vector<float, 4>(v4.y, v4.z, v4.y, v4.y));
	REQUIRE(swizzle::yzyz(v4) == vector<float, 4>(v4.y, v4.z, v4.y, v4.z));
	REQUIRE(swizzle::yzzw(v4) == vector<float, 4>(v4.y, v4.z, v4.z, v4.w));
	REQUIRE(swizzle::yzzx(v4) == vector<float, 4>(v4.y, v4.z, v4.z, v4.x));
	REQUIRE(swizzle::yzzy(v4) == vector<float, 4>(v4.y, v4.z, v4.z, v4.y));
	REQUIRE(swizzle::yzzz(v4) == vector<float, 4>(v4.y, v4.z, v4.z, v4.z));
	REQUIRE(swizzle::zwww(v4) == vector<float, 4>(v4.z, v4.w, v4.w, v4.w));
	REQUIRE(swizzle::zwwx(v4) == vector<float, 4>(v4.z, v4.w, v4.w, v4.x));
	REQUIRE(swizzle::zwwy(v4) == vector<float, 4>(v4.z, v4.w, v4.w, v4.y));
	REQUIRE(swizzle::zwwz(v4) == vector<float, 4>(v4.z, v4.w, v4.w, v4.z));
	REQUIRE(swizzle::zwxw(v4) == vector<float, 4>(v4.z, v4.w, v4.x, v4.w));
	REQUIRE(swizzle::zwxx(v4) == vector<float, 4>(v4.z, v4.w, v4.x, v4.x));
	REQUIRE(swizzle::zwxy(v4) == vector<float, 4>(v4.z, v4.w, v4.x, v4.y));
	REQUIRE(swizzle::zwxz(v4) == vector<float, 4>(v4.z, v4.w, v4.x, v4.z));
	REQUIRE(swizzle::zwyw(v4) == vector<float, 4>(v4.z, v4.w, v4.y, v4.w));
	REQUIRE(swizzle::zwyx(v4) == vector<float, 4>(v4.z, v4.w, v4.y, v4.x));
	REQUIRE(swizzle::zwyy(v4) == vector<float, 4>(v4.z, v4.w, v4.y, v4.y));
	REQUIRE(swizzle::zwyz(v4) == vector<float, 4>(v4.z, v4.w, v4.y, v4.z));
	REQUIRE(swizzle::zwzw(v4) == vector<float, 4>(v4.z, v4.w, v4.z, v4.w));
	REQUIRE(swizzle::zwzx(v4) == vector<float, 4>(v4.z, v4.w, v4.z, v4.x));
	REQUIRE(swizzle::zwzy(v4) == vector<float, 4>(v4.z, v4.w, v4.z, v4.y));
	REQUIRE(swizzle::zwzz(v4) == vector<float, 4>(v4.z, v4.w, v4.z, v4.z));
	REQUIRE(swizzle::zxww(v4) == vector<float, 4>(v4.z, v4.x, v4.w, v4.w));
	REQUIRE(swizzle::zxwx(v4) == vector<float, 4>(v4.z, v4.x, v4.w, v4.x));
	REQUIRE(swizzle::zxwy(v4) == vector<float, 4>(v4.z, v4.x, v4.w, v4.y));
	REQUIRE(swizzle::zxwz(v4) == vector<float, 4>(v4.z, v4.x, v4.w, v4.z));
	REQUIRE(swizzle::zxxw(v4) == vector<float, 4>(v4.z, v4.x, v4.x, v4.w));
	REQUIRE(swizzle::zxxx(v4) == vector<float, 4>(v4.z, v4.x, v4.x, v4.x));
	REQUIRE(swizzle::zxxy(v4) == vector<float, 4>(v4.z, v4.x, v4.x, v4.y));
	REQUIRE(swizzle::zxxz(v4) == vector<float, 4>(v4.z, v4.x, v4.x, v4.z));
	REQUIRE(swizzle::zxyw(v4) == vector<float, 4>(v4.z, v4.x, v4.y, v4.w));
	REQUIRE(swizzle::zxyx(v4) == vector<float, 4>(v4.z, v4.x, v4.y, v4.x));
	REQUIRE(swizzle::zxyy(v4) == vector<float, 4>(v4.z, v4.x, v4.y, v4.y));
	REQUIRE(swizzle::zxyz(v4) == vector<float, 4>(v4.z, v4.x, v4.y, v4.z));
	REQUIRE(swizzle::zxzw(v4) == vector<float, 4>(v4.z, v4.x, v4.z, v4.w));
	REQUIRE(swizzle::zxzx(v4) == vector<float, 4>(v4.z, v4.x, v4.z, v4.x));
	REQUIRE(swizzle::zxzy(v4) == vector<float, 4>(v4.z, v4.x, v4.z, v4.y));
	REQUIRE(swizzle::zxzz(v4) == vector<float, 4>(v4.z, v4.x, v4.z, v4.z));
	REQUIRE(swizzle::zyww(v4) == vector<float, 4>(v4.z, v4.y, v4.w, v4.w));
	REQUIRE(swizzle::zywx(v4) == vector<float, 4>(v4.z, v4.y, v4.w, v4.x));
	REQUIRE(swizzle::zywy(v4) == vector<float, 4>(v4.z, v4.y, v4.w, v4.y));
	REQUIRE(swizzle::zywz(v4) == vector<float, 4>(v4.z, v4.y, v4.w, v4.z));
	REQUIRE(swizzle::zyxw(v4) == vector<float, 4>(v4.z, v4.y, v4.x, v4.w));
	REQUIRE(swizzle::zyxx(v4) == vector<float, 4>(v4.z, v4.y, v4.x, v4.x));
	REQUIRE(swizzle::zyxy(v4) == vector<float, 4>(v4.z, v4.y, v4.x, v4.y));
	REQUIRE(swizzle::zyxz(v4) == vector<float, 4>(v4.z, v4.y, v4.x, v4.z));
	REQUIRE(swizzle::zyyw(v4) == vector<float, 4>(v4.z, v4.y, v4.y, v4.w));
	REQUIRE(swizzle::zyyx(v4) == vector<float, 4>(v4.z, v4.y, v4.y, v4.x));
	REQUIRE(swizzle::zyyy(v4) == vector<float, 4>(v4.z, v4.y, v4.y, v4.y));
	REQUIRE(swizzle::zyyz(v4) == vector<float, 4>(v4.z, v4.y, v4.y, v4.z));
	REQUIRE(swizzle::zyzw(v4) == vector<float, 4>(v4.z, v4.y, v4.z, v4.w));
	REQUIRE(swizzle::zyzx(v4) == vector<float, 4>(v4.z, v4.y, v4.z, v4.x));
	REQUIRE(swizzle::zyzy(v4) == vector<float, 4>(v4.z, v4.y, v4.z, v4.y));
	REQUIRE(swizzle::zyzz(v4) == vector<float, 4>(v4.z, v4.y, v4.z, v4.z));
	REQUIRE(swizzle::zzww(v4) == vector<float, 4>(v4.z, v4.z, v4.w, v4.w));
	REQUIRE(swizzle::zzwx(v4) == vector<float, 4>(v4.z, v4.z, v4.w, v4.x));
	REQUIRE(swizzle::zzwy(v4) == vector<float, 4>(v4.z, v4.z, v4.w, v4.y));
	REQUIRE(swizzle::zzwz(v4) == vector<float, 4>(v4.z, v4.z, v4.w, v4.z));
	REQUIRE(swizzle::zzxw(v4) == vector<float, 4>(v4.z, v4.z, v4.x, v4.w));
	REQUIRE(swizzle::zzxx(v4) == vector<float, 4>(v4.z, v4.z, v4.x, v4.x));
	REQUIRE(swizzle::zzxy(v4) == vector<float, 4>(v4.z, v4.z, v4.x, v4.y));
	REQUIRE(swizzle::zzxz(v4) == vector<float, 4>(v4.z, v4.z, v4.x, v4.z));
	REQUIRE(swizzle::zzyw(v4) == vector<float, 4>(v4.z, v4.z, v4.y, v4.w));
	REQUIRE(swizzle::zzyx(v4) == vector<float, 4>(v4.z, v4.z, v4.y, v4.x));
	REQUIRE(swizzle::zzyy(v4) == vector<float, 4>(v4.z, v4.z, v4.y, v4.y));
	REQUIRE(swizzle::zzyz(v4) == vector<float, 4>(v4.z, v4.z, v4.y, v4.z));
	REQUIRE(swizzle::zzzw(v4) == vector<float, 4>(v4.z, v4.z, v4.z, v4.w));
	REQUIRE(swizzle::zzzx(v4) == vector<float, 4>(v4.z, v4.z, v4.z, v4.x));
	REQUIRE(swizzle::zzzy(v4) == vector<float, 4>(v4.z, v4.z, v4.z, v4.y));
	REQUIRE(swizzle::zzzz(v4) == vector<float, 4>(v4.z, v4.z, v4.z, v4.z));
}


