name: Check Licenses


on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:

   check:

    # Run on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake --preset ci-licenses

    - name: Build Project
      run: cmake --build --preset ci-licenses

    - name: Run checker
      working-directory: build
      run: ./util_update_licenses ${{ github.workspace }} --fail-on-missmatch
