name: Code Coverage


on:
  pull_request:
    branches: [ main, develop ]

jobs:

  codecov:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DMST_RUN_TESTS=True

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE --parallel 10
      
    - name: Upload coverage to Codecov
      working-directory: ${{runner.workspace}}/build
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        wget https://codecov.io/bash -O codecov
        chmod +x codecov
        ./codecov -t $CODECOV_TOKEN -B $GITHUB_REF -s .
