name: Code Coverage


on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:

   codecov:

    # Run on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake --preset ci-coverage

    - name: Build Project
      run: cmake --build --preset ci-coverage

    - name: Run tests
      run: ctest --preset ci-coverage

    - name: Collect data
      working-directory: build
      run: |
        sudo apt install lcov
        lcov -c -d . -o coverage.info --ignore-errors mismatch,source
        lcov -r coverage.info '*/_deps/*' '/usr/*' -o coverage.info --ignore-errors unused
        lcov -l coverage.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: build/coverage.info
        name: mst
        fail_ci_if_error: true
