name: Unit Tests

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  msvc-unit-tests:
    name: MSVC Unit Tests

    # Run on Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      shell: bash
      run: cmake --preset ci-tests

    - name: Build
      shell: bash
      run: cmake --build --preset ci-tests

    - name: Test
      shell: bash
      run: ctest --preset ci-tests

  clang-unit-tests:
    name: Clang Unit Tests
    strategy:
      matrix:
        platforms: [ubuntu-latest, macos-latest, arm-cpu]

    runs-on: ${{ matrix.platforms }}

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      shell: bash
      run: cmake --preset ci-tests
      env:
        CXX: clang++
        CC: clang

    - name: Build
      shell: bash
      run: cmake --build --preset ci-tests

    - name: Test
      shell: bash
      run: ctest --preset ci-tests

  gcc-unit-tests:
    name: GCC Unit Tests
    strategy:
      matrix:
        platforms: [ubuntu-latest, arm-cpu]

    runs-on: ${{ matrix.platforms }}

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      shell: bash
      run: cmake --preset ci-tests
      env:
        CXX: g++
        CC: gcc

    - name: Build
      shell: bash
      run: cmake --build --preset ci-tests

    - name: Test
      shell: bash
      run: ctest --preset ci-tests
